// The icons: Google's Material icons, filled, a few hundred of them in
// categories, generated by the Android twin's tools/generate_icons.py into
// Icons.json — the very file Android ships, byte for byte, so an icon is the
// same outline on both phones. Apache-2.0; the licence is bundled beside it
// (MaterialIcons-LICENSE.txt).
//
// An icon goes on the page as a shape drawn from its own path, as a chart's
// slice is, so recolouring, borders, shadows and export already work, and a
// build that knows nothing of icons still draws it. The element keeps the
// icon's id (`iconId`) to be named by, and for a replace to come.

import Foundation

/// One icon: its Material name as its id, what the sheet calls it, its
/// category, a few words to find it by, and its outline in the 0…100 box.
struct IconDef: Codable, Identifiable, Equatable {
    var id: String
    var name: String
    var category: String
    var tags: [String] = []
    var path: String

    private enum CodingKeys: String, CodingKey { case id, name, category, tags, path }

    init(id: String, name: String, category: String, tags: [String] = [], path: String) {
        self.id = id
        self.name = name
        self.category = category
        self.tags = tags
        self.path = path
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id = try c.decode(String.self, forKey: .id)
        name = try c.decode(String.self, forKey: .name)
        category = try c.decode(String.self, forKey: .category)
        tags = (try? c.decodeIfPresent([String].self, forKey: .tags)) ?? []
        path = try c.decode(String.self, forKey: .path)
    }

    /// The icon as a library shape, for a tile to draw.
    var shape: ShapeDef {
        ShapeDef(id: id, name: name, category: category, path: path, rectLike: false)
    }
}

/// One category's icons, as the sheet shows them under one heading.
struct IconGroup: Identifiable {
    var category: String
    var icons: [IconDef]

    var id: String { category }
}

enum IconLibrary {

    /// An icon's side as it goes on the page, whatever the page.
    static let side: Double = 160

    /// The file's shape. Other top-level keys ("source") are informational.
    private struct File: Codable {
        var categories: [String]
        var icons: [IconDef]
    }

    /// Read once, on first use.
    private static let file: File = {
        guard let url = Bundle.main.url(forResource: "Icons", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let decoded = try? JSONDecoder().decode(File.self, from: data) else {
            assertionFailure("Icons.json missing or invalid")
            return File(categories: [], icons: [])
        }
        return decoded
    }()

    /// Every icon, category by category, in the generator's order.
    static var icons: [IconDef] { file.icons }

    /// The categories, in the order the sheet shows them.
    static var categories: [String] { file.categories }

    // A duplicate id would be a content bug, not a reason to trap: keep the
    // first, as ContentLibrary.shapeMap does.
    private static let byId: [String: IconDef] = Dictionary(
        file.icons.map { ($0.id, $0) }, uniquingKeysWith: { first, _ in first })

    static func icon(_ id: String?) -> IconDef? {
        id.flatMap { byId[$0] }
    }

    /// The icons whose name, id or one of whose tags has `query` in it, case
    /// aside; every icon for a blank one. As the Android twin's search.
    static func search(_ query: String) -> [IconDef] {
        let needle = query.trimmingCharacters(in: .whitespaces).lowercased()
        guard !needle.isEmpty else { return icons }
        return icons.filter { icon in
            icon.name.lowercased().contains(needle) || icon.id.contains(needle)
                || icon.tags.contains { $0.contains(needle) }
        }
    }

    /// What `search` finds, by category in sheet order; a category with
    /// nothing found drops out.
    static func grouped(_ query: String) -> [IconGroup] {
        let found = Dictionary(grouping: search(query), by: \.category)
        return categories.compactMap { category in
            found[category].map { IconGroup(category: category, icons: $0) }
        }
    }

    /// The icon an element was put on as, when it is one this library has.
    static func icon(of el: Element) -> IconDef? {
        icon(el.iconId)
    }

    /// What an icon is filled with: the brand kit's first colour when the
    /// kit has one, else ink that reads on the page.
    static func fill(for page: Page, brandColours: [String]) -> String {
        brandColours.first ?? DataGraphics.ink(for: page)
    }

    /// `icon` as a shape `side` square in the middle of a page this size,
    /// filled solid with `fill`, drawn from its path (`pathData`) and naming
    /// it (`iconId`).
    static func element(_ icon: IconDef, pageWidth: Double, pageHeight: Double, fill: String) -> Element {
        var el = Element.shape("rect", w: side, h: side)
        el.x = (pageWidth - side) / 2
        el.y = (pageHeight - side) / 2
        el.fill = .solid(fill)
        el.pathData = icon.path
        el.iconId = icon.id
        return el
    }
}
